common: &default_settings
  license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  app_name: Soccer Expenses
  log_level: info

staging:
  <<: *default_settings
  app_name: Soccer Expenses (Staging)

production:
  <<: *default_settings
